import { BookOpenText, CheckCircle2, ListChecks, Loader2, PenLine, Sparkles, Star, Volume2 } from 'lucide-react'
import { useEffect, useState, type ReactNode } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { api, ApiError } from '../lib/api'
import { PATTERN_LABEL, SKILL_LABEL, fmtDate, pct, speak } from '../lib/format'
import type { Activity, AttemptResult } from '../lib/types'
import { EmptyState, ErrorBox, Spinner } from './ui'

export const KIND_META: Record<Activity['kind'], { label: string; icon: ReactNode; tint: string }> = {
  word_practice: { label: 'Spot the word', icon: <ListChecks className="h-5 w-5" />, tint: 'bg-teal-100 text-teal-700' },
  spelling: { label: 'Listen & spell', icon: <PenLine className="h-5 w-5" />, tint: 'bg-lavender-100 text-lavender-600' },
  reading: { label: 'Read aloud', icon: <Volume2 className="h-5 w-5" />, tint: 'bg-sun-100 text-sun-700' },
  story: { label: 'Story time', icon: <BookOpenText className="h-5 w-5" />, tint: 'bg-cream-200 text-navy-700' },
}

export function SourceBadge({ source }: { source: Activity['source'] }) {
  return source === 'gemini'
    ? <span className="badge bg-lavender-100 text-lavender-600" title="Generated by Gemini and validated locally">AI-generated</span>
    : <span className="badge bg-cream-200 text-navy-700" title="Built by Lexora's local deterministic generator from the child's error profile">Local generator</span>
}

export function PracticeList({ childId, canGenerate, openHref, sessionId }: { childId: number; canGenerate: boolean; openHref: (a: Activity) => string; sessionId?: number }) {
  const [items, setItems] = useState<Activity[] | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)
  const load = () => api.practice(childId).then(setItems).catch((e) => setError(e.message))
  useEffect(() => { load() /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [childId])

  const generate = async () => {
    setBusy(true); setError(null)
    try { await api.generatePractice(childId, sessionId); await load() }
    catch (e) { setError(e instanceof ApiError ? e.message : 'Could not generate') }
    finally { setBusy(false) }
  }

  if (error) return <ErrorBox message={error} onRetry={load} />
  if (!items) return <Spinner />

  return (
    <div className="space-y-4">
      {canGenerate && (
        <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-dashed border-cream-300 p-4">
          <p className="text-sm text-navy-500">{items.length ? 'Generate a fresh set from the latest screening’s error profile.' : 'No practice yet. Generate a set from the latest screening (or starter practice if none).'}</p>
          <button className="btn-teal" onClick={generate} disabled={busy}>{busy ? <><Loader2 className="h-4 w-4 animate-spin" />Generating…</> : <><Sparkles className="h-4 w-4" />Generate practice</>}</button>
        </div>
      )}
      {items.length === 0 ? (
        <EmptyState icon={<Sparkles className="h-6 w-6" />} title="No practice activities yet" body={canGenerate ? 'Use the button above to create a personalised set.' : 'Your teacher will add practice after a screening.'} />
      ) : (
        <ul className="grid gap-3 sm:grid-cols-2">
          {items.map((a) => {
            const m = KIND_META[a.kind]
            return (
              <li key={a.id}>
                <Link to={openHref(a)} className="card flex h-full gap-4 p-4 transition hover:-translate-y-0.5 hover:shadow-lg">
                  <div className={`grid h-12 w-12 shrink-0 place-items-center rounded-xl ${m.tint}`}>{m.icon}</div>
                  <div className="min-w-0 flex-1">
                    <div className="flex items-start justify-between gap-2">
                      <p className="font-bold leading-tight">{a.title}</p>
                      {a.best_score !== null && <span className="badge bg-teal-100 text-teal-700"><Star className="h-3 w-3" />{pct(a.best_score)}</span>}
                    </div>
                    <p className="text-xs text-navy-500">{m.label} · {fmtDate(a.created_at)}{a.attempt_count ? ` · ${a.attempt_count} ${a.attempt_count === 1 ? 'try' : 'tries'}` : ''}</p>
                    <div className="mt-2 flex flex-wrap gap-1">{a.target_skills.map((s) => <span key={s} className="badge bg-cream-100 text-navy-700">{SKILL_LABEL[s] ?? s}</span>)}<SourceBadge source={a.source} /></div>
                  </div>
                </Link>
              </li>
            )
          })}
        </ul>
      )}
    </div>
  )
}

/** The child-facing activity player. */
export function PracticePlayer({ activity, backHref }: { activity: Activity; backHref: string }) {
  const nav = useNavigate()
  const c = activity.content
  const [answers, setAnswers] = useState<Record<string, unknown>>({})
  const [result, setResult] = useState<AttemptResult | null>(null)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const m = KIND_META[c.kind]
  const total = c.kind === 'word_practice' ? c.word_choice.length : c.kind === 'spelling' ? c.spelling.length : c.kind === 'reading' ? c.reading.length : c.questions.length
  const answered = Object.keys(answers).length
  const set = (i: number, v: unknown) => setAnswers((a) => ({ ...a, [String(i)]: v }))

  const submit = async () => {
    setBusy(true); setError(null)
    try { setResult(await api.submitAttempt(activity.id, answers)) }
    catch (e) { setError(e instanceof ApiError ? e.message : 'Could not save') }
    finally { setBusy(false) }
  }

  if (result) {
    const stars = result.score >= 0.9 ? 3 : result.score >= 0.6 ? 2 : 1
    return (
      <div className="card mx-auto max-w-xl p-8 text-center">
        <div className="flex justify-center gap-1">{[0, 1, 2].map((i) => <Star key={i} className={`h-10 w-10 ${i < stars ? 'fill-sun-500 text-sun-500' : 'text-cream-300'}`} />)}</div>
        <h2 className="mt-4 text-2xl font-bold">{result.correct} of {result.total} right!</h2>
        <p className="mt-1 text-navy-500">{stars === 3 ? 'Brilliant work.' : stars === 2 ? 'Good going — keep practising.' : 'Nice try! Every go makes you stronger.'}</p>
        {c.kind !== 'reading' && (
          <ul className="mt-5 space-y-1.5 text-left text-sm">
            {result.feedback.map((f) => (
              <li key={f.index} className={`flex items-start gap-2 rounded-xl px-3 py-2 ${f.correct ? 'bg-teal-100/60' : 'bg-cream-100'}`}>
                <CheckCircle2 className={`mt-0.5 h-4 w-4 shrink-0 ${f.correct ? 'text-teal-700' : 'text-cream-300'}`} />
                <span>
                  <strong>{f.expected}</strong>{!f.correct && <> — you wrote <em>{f.given || 'nothing'}</em></>}
                  {f.patterns && f.patterns.length > 0 && <span className="block text-xs text-navy-500">{f.patterns.map((p) => PATTERN_LABEL[p] ?? p).join(', ')}</span>}
                </span>
              </li>
            ))}
          </ul>
        )}
        <div className="mt-6 flex justify-center gap-3">
          <button className="btn-secondary" onClick={() => { setResult(null); setAnswers({}) }}>Try again</button>
          <button className="btn-primary" onClick={() => nav(backHref)}>More practice</button>
        </div>
      </div>
    )
  }

  return (
    <div className="mx-auto max-w-2xl">
      <div className="mb-4 flex items-center gap-3">
        <div className={`grid h-12 w-12 place-items-center rounded-xl ${m.tint}`}>{m.icon}</div>
        <div><h1 className="text-2xl font-bold">{c.title}</h1><p className="text-sm text-navy-500">{c.instructions}</p></div>
      </div>
      <div className="mb-3 flex items-center gap-2 text-xs"><SourceBadge source={activity.source} /><span className="text-navy-500">{c.target_skills.map((s) => SKILL_LABEL[s] ?? s).join(' · ')}</span></div>

      <div className="space-y-3">
        {c.kind === 'word_practice' && c.word_choice.map((it, i) => (
          <div key={i} className="card p-4">
            <div className="mb-3 flex items-center justify-between"><span className="text-sm font-bold text-navy-500">Word {i + 1}</span><button className="btn-secondary" onClick={() => speak(it.prompt)}><Volume2 className="h-4 w-4" />Hear it</button></div>
            <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
              {it.options.map((o) => (
                <button key={o} onClick={() => set(i, o)} className={`rounded-xl border-2 px-3 py-3 font-display text-2xl font-bold transition ${answers[String(i)] === o ? 'border-teal-500 bg-teal-100' : 'border-cream-200 bg-white hover:border-lavender-400'}`}>{o}</button>
              ))}
            </div>
          </div>
        ))}
        {c.kind === 'spelling' && c.spelling.map((it, i) => (
          <div key={i} className="card flex flex-wrap items-center gap-3 p-4">
            <button className="btn-secondary" onClick={() => speak(it.word)}><Volume2 className="h-4 w-4" />Play word {i + 1}</button>
            <input className="input min-w-[160px] flex-1 font-display text-xl" placeholder="type it here" autoCapitalize="off" autoComplete="off" spellCheck={false}
              value={(answers[String(i)] as string) ?? ''} onChange={(e) => set(i, e.target.value)} />
            {it.hint && <p className="w-full text-xs text-navy-500">Hint: {it.hint}</p>}
          </div>
        ))}
        {c.kind === 'reading' && c.reading.map((it, i) => (
          <div key={i} className="card flex flex-wrap items-center justify-between gap-3 p-4">
            <p className="font-display text-2xl font-bold">{it.sentence}</p>
            <div className="flex gap-2">
              <button className="btn-ghost" onClick={() => speak(it.sentence)} aria-label="Hear this sentence"><Volume2 className="h-4 w-4" /></button>
              <button onClick={() => set(i, !answers[String(i)])} className={answers[String(i)] ? 'btn-teal' : 'btn-secondary'}><CheckCircle2 className="h-4 w-4" />{answers[String(i)] ? 'Read it!' : 'I read it'}</button>
            </div>
          </div>
        ))}
        {c.kind === 'story' && (
          <>
            <div className="card p-6">
              <div className="mb-3 flex justify-end"><button className="btn-secondary" onClick={() => speak(c.story_text)}><Volume2 className="h-4 w-4" />Read to me</button></div>
              <p className="font-display text-2xl leading-relaxed">{c.story_text}</p>
            </div>
            {c.questions.map((q, i) => (
              <div key={i} className="card p-4">
                <p className="mb-3 font-bold">{q.question}</p>
                <div className="grid gap-2 sm:grid-cols-3">
                  {q.options.map((o) => <button key={o} onClick={() => set(i, o)} className={`rounded-xl border-2 px-3 py-2.5 font-bold transition ${answers[String(i)] === o ? 'border-teal-500 bg-teal-100' : 'border-cream-200 bg-white hover:border-lavender-400'}`}>{o}</button>)}
                </div>
              </div>
            ))}
          </>
        )}
      </div>

      {error && <div className="mt-4"><ErrorBox message={error} /></div>}
      <div className="mt-6 flex items-center justify-between">
        <Link to={backHref} className="btn-ghost">Back</Link>
        <button className="btn-primary btn-lg" onClick={submit} disabled={busy || answered < total}>{busy ? 'Saving…' : answered < total ? `${total - answered} left` : 'Check my answers'}</button>
      </div>
    </div>
  )
}
